const API='/api/v1';
const q=(s,r=document)=>r.querySelector(s); const qa=(s,r=document)=>[...r.querySelectorAll(s)];
let activeWorkspace=null; let registry=[]; let dirty=false;
async function api(path,options={}){const res=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const body=await res.json();if(!body.ok)throw new Error(body.error?.message||'Request failed');return body.data;}
function notice(title,message=''){const region=q('#toastRegion');if(!region)return;const el=document.createElement('div');el.className='toast';el.innerHTML=`<strong>${title}</strong><span>${message}</span>`;region.append(el);setTimeout(()=>el.remove(),3500)}
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'workspace';}
function snapshotWidgets(){return qa('#workspaceGrid .widget').map((node,index)=>({id:node.dataset.instanceId||`widget-${index+1}`,type:node.dataset.widget||node.dataset.widgetType||node.id?.replace(/^widget-/,'')||'custom',position:{x:index%12,y:Math.floor(index/3)*3},size:{w:Number(node.dataset.w||4),h:Number(node.dataset.h||3)},settings:JSON.parse(node.dataset.settings||'{}'),visibility:!node.hidden}));}
function applyWorkspace(ws){activeWorkspace=ws; q('#workspaceSelect').innerHTML=`<option>${ws.name}</option>`; const known=new Map(snapshotWidgets().map(x=>[x.type,x])); qa('#workspaceGrid .widget').forEach(n=>n.hidden=true); ws.widgets.forEach((item,index)=>{let node=q(`#workspaceGrid .widget[data-widget="${item.type}"]`)||q(`#workspaceGrid #widget-${item.type}`); if(node){node.hidden=item.visibility===false;node.dataset.instanceId=item.id;node.dataset.w=item.size?.w||4;node.dataset.h=item.size?.h||3;node.style.gridColumn=`span ${Math.min(12,Math.max(2,item.size?.w||4))}`;node.style.order=String(index);}}); dirty=false;document.body.dataset.workspaceId=ws.id;}
async function load(){const [spaces,widgets]=await Promise.all([api('/workspaces'),api('/widgets/registry')]);registry=widgets;const ws=spaces.items.find(x=>x.id===spaces.activeWorkspaceId)||spaces.items[0];if(ws)applyWorkspace(ws);wireWorkspaceControls();}
async function save(){if(!activeWorkspace)return;const payload={...activeWorkspace,widgets:snapshotWidgets(),updatedAt:Date.now()};activeWorkspace=await api(`/workspaces/${activeWorkspace.id}`,{method:'PUT',body:JSON.stringify(payload)});dirty=false;notice('Workspace saved',`${activeWorkspace.widgets.length} widget placements persisted to the backend.`);}
function mark(){dirty=true;q('#customizeBanner')?.removeAttribute('hidden');}
function addWidget(type){const existing=q(`#workspaceGrid .widget[data-widget="${type}"]`)||q(`#workspaceGrid #widget-${type}`);if(existing){existing.hidden=false;existing.style.order='999';existing.dataset.instanceId=`widget-${type}-${Date.now()}`;mark();notice('Widget added',registry.find(x=>x.type===type)?.name||type);return;}notice('Widget unavailable','This widget type has no renderer in the Phase 3 shell yet.');}
function exportWorkspace(){const blob=new Blob([JSON.stringify({...activeWorkspace,widgets:snapshotWidgets()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${slug(activeWorkspace.name)}.workspace.json`;a.click();URL.revokeObjectURL(a.href);}
function importWorkspace(file){const r=new FileReader();r.onload=async()=>{try{const ws=JSON.parse(r.result);ws.id=`workspace-${Date.now()}`;ws.name=`${ws.name||'Imported'} copy`;const created=await api('/workspaces',{method:'POST',body:JSON.stringify(ws)});applyWorkspace(created);notice('Workspace imported',created.name);}catch(e){notice('Import failed',e.message)}};r.readAsText(file);}
function wireWorkspaceControls(){q('#doneCustomizeBtn')?.addEventListener('click',save);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();}});q('#widgetCatalog')?.addEventListener('click',e=>{const b=e.target.closest('[data-widget]');if(b)addWidget(b.dataset.widget)});q('#inspectorContent')?.addEventListener('click',e=>{const text=e.target.textContent.trim();if(text==='Export workspace JSON')exportWorkspace();if(text==='Import workspace JSON'){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>i.files[0]&&importWorkspace(i.files[0]);i.click();}});q('#workspaceSelect')?.addEventListener('dblclick',async()=>{const name=prompt('New workspace name','Monitoring');if(!name)return;const copy={...activeWorkspace,id:`workspace-${slug(name)}-${Date.now().toString().slice(-5)}`,name,widgets:snapshotWidgets()};delete copy.createdAt;delete copy.updatedAt;const created=await api('/workspaces',{method:'POST',body:JSON.stringify(copy)});applyWorkspace(created);notice('Workspace created',name)});}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
load().catch(e=>notice('Workspace API unavailable',e.message));
