import {api,ApiError} from './api.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={machines:[],models:[],profiles:[],jobs:[],status:null,telemetry:null,logs:[],requests:null,gateway:null,capabilities:null,workspace:null,registry:[]};
function toast(t,m='',k='neutral'){const r=$('#toastRegion');if(!r)return;const e=document.createElement('div');e.className=`toast ${k}`;e.innerHTML=`<strong>${esc(t)}</strong><span>${esc(m)}</span>`;r.append(e);setTimeout(()=>e.remove(),4000)}
function err(e){return e instanceof ApiError?`${e.code}: ${e.message}`:(e?.message||String(e))}
function badge(t,k='neutral'){return `<span class="status-badge ${k}">${esc(t)}</span>`}
function neutralize(){
 const h=$('.global-health');if(h)h.innerHTML='<div class="health-pill neutral" id="hHost"><span></span> Host unknown</div><div class="health-pill neutral" id="hMachines"><span></span> Machines unknown</div><div class="health-pill neutral" id="hOpenAI">OpenAI unknown</div><div class="health-pill neutral" id="hOllama">Ollama unknown</div>';
 const r=$('[data-widget-id="runtime"]');if(r)r.innerHTML='<header class="widget-header"><div><span class="widget-kicker">ACTIVE RUNTIME</span><h2 id="rtTitle">Unknown</h2></div><span id="rtBadge" class="status-badge neutral">Loading</span></header><div id="rtBody" class="runtime-layout"><div class="empty-state"><p>Loading runtime evidence…</p></div></div>';
 const t=$('[data-widget-id="topology"]');if(t)t.innerHTML='<header class="widget-header"><div><span class="widget-kicker">DISTRIBUTED RUNTIME</span><h2>Machine topology</h2></div><button class="button compact secondary add-machine-trigger">＋ Add machine</button></header><div id="topologySummary" class="topology-toolbar">Loading</div><div id="topologyCanvas" class="topology-canvas"><div class="empty-state"><p>Loading machines…</p></div></div>';
 const tm=$('[data-widget-id="telemetry"]');if(tm)tm.innerHTML='<header class="widget-header"><div><span class="widget-kicker">LIVE TELEMETRY</span><h2>Performance</h2></div></header><div id="telemetryTruth"><div class="empty-state"><p>Loading telemetry…</p></div></div>';
 const rq=$('[data-widget-id="requests"]');if(rq)rq.innerHTML='<header class="widget-header"><div><span class="widget-kicker">REQUESTS</span><h2>Active requests</h2></div></header><div class="data-table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Route</th><th>State</th><th></th></tr></thead><tbody id="requestTruth"><tr><td colspan="4">Loading…</td></tr></tbody></table></div>';
 const ev=$('[data-widget-id="evidence"]');if(ev)ev.innerHTML='<header class="widget-header"><div><span class="widget-kicker">EVIDENCE</span><h2>Runtime activity</h2></div></header><div id="evidenceTruth" class="event-list"><div class="empty-state"><p>No evidence loaded.</p></div></div>';
 if($('#modelsTableBody'))$('#modelsTableBody').innerHTML='<tr><td colspan="9">Loading models…</td></tr>';if($('#machineGrid'))$('#machineGrid').innerHTML='<div class="empty-state"><p>Loading machines…</p></div>';
 const log=$('.log-console pre');if(log)log.textContent='Loading logs…';const pg=$('.profile-grid');if(pg)pg.innerHTML='<div class="content-card"><p>Loading profiles…</p></div>';const eg=$('.endpoint-grid');if(eg)eg.innerHTML='<div class="content-card"><p>Loading gateway status…</p></div>';
}
function nav(){$$('.nav-item[data-page]').forEach(b=>b.addEventListener('click',()=>{$$('.nav-item[data-page]').forEach(x=>x.classList.toggle('active',x===b));$$('.page[data-page-view]').forEach(p=>p.classList.toggle('active',p.dataset.pageView===b.dataset.page))}))}
function renderStatus(){const rt=S.status?.runtime||{}, p=rt.process||{};$('#hHost').innerHTML=`<span></span> Host ${p.running?'ready':esc(rt.state||'unknown')}`;$('#hHost').className=`health-pill ${p.running?'good':'neutral'}`;const ok=S.machines.filter(m=>['reachable','online'].includes(m.status)).length;$('#hMachines').innerHTML=`<span></span> ${ok}/${S.machines.length} tested reachable`;$('#rtTitle').textContent=S.models.find(m=>m.id===rt.activeModelId)?.name||rt.activeModelId||'No active model';$('#rtBadge').textContent=rt.state||'unknown';$('#rtBody').innerHTML=`<div class="runtime-stats"><div class="metric"><span>State</span><strong>${esc(rt.state||'unknown')}</strong><small>Backend</small></div><div class="metric"><span>Process</span><strong>${p.running?'Running':'Stopped'}</strong><small>${p.pid?`PID ${esc(p.pid)}`:'No PID'}</small></div><div class="metric"><span>Jobs</span><strong>${S.jobs.length}</strong><small>Backend store</small></div></div><div class="runtime-actions"><button id="launchReal" class="button primary">Launch model</button><button id="stopReal" class="button danger-soft">Stop runtime</button></div>`;$('#launchReal').onclick=launch;$('#stopReal').onclick=stop}
function renderMachines(){const cards=S.machines.length?S.machines.map(m=>`<article class="content-card machine-card"><div class="section-head"><div><h3>${esc(m.name)}</h3><code>${esc(m.addresses?.[0]||'Unknown')}</code></div>${badge(m.status||'unknown',['reachable','online'].includes(m.status)?'good':m.status==='offline'?'warning':'neutral')}</div><p>Controller :${esc(m.controller?.port||'unknown')} · RPC :${esc(m.rpc?.port||'unknown')}</p><div class="runtime-actions"><button class="button compact secondary testReal" data-id="${esc(m.id)}">Test</button><button class="button compact secondary rpcStart" data-id="${esc(m.id)}">Start RPC</button><button class="button compact secondary rpcStop" data-id="${esc(m.id)}">Stop RPC</button></div></article>`).join(''):'<div class="empty-state"><p>No machines registered.</p></div>';$('#machineGrid').innerHTML=cards;$('#topologyCanvas').innerHTML=S.machines.length?S.machines.map(m=>`<div class="machine-node"><div class="node-head"><span class="status-dot ${['reachable','online'].includes(m.status)?'good':'neutral'}"></span><strong>${esc(m.name)}</strong><small>${esc(m.addresses?.[0]||'Unknown')}</small></div><div class="node-grid"><span>Status</span><b>${esc(m.status||'unknown')}</b><span>RPC</span><b>:${esc(m.rpc?.port||'unknown')}</b></div></div>`).join(''):'No machines';$('#topologySummary').innerHTML=badge(`${S.machines.filter(m=>['reachable','online'].includes(m.status)).length}/${S.machines.length} tested reachable`);$$('.testReal').forEach(b=>b.onclick=()=>testMachine(b.dataset.id));$$('.rpcStart').forEach(b=>b.onclick=()=>rpc(b.dataset.id,'start'));$$('.rpcStop').forEach(b=>b.onclick=()=>rpc(b.dataset.id,'stop'))}
async function testMachine(id){try{const r=await api.testMachine(id);toast(r.reachable?'Machine reachable':'Machine offline',r.diagnostic||`${r.latencyMs} ms`,r.reachable?'good':'warning');await refresh()}catch(e){toast('Machine test failed',err(e),'warning')}}
async function rpc(id,a){try{const j=a==='start'?await api.rpcStart(id):await api.rpcStop(id);toast(`RPC ${a} accepted`,j.id);await waitJob(j.id);await refresh()}catch(e){toast(`RPC ${a} failed`,err(e),'warning')}}
function renderModels(){const b=$('#modelsTableBody');b.innerHTML=S.models.length?S.models.map(m=>`<tr><td><strong>${esc(m.name||m.filename||m.id)}</strong><small>${esc(m.path||'')}</small></td><td>${esc(m.architecture||m.metadata?.architecture||'Unknown')}</td><td>${esc(m.quantization||m.metadata?.fileType||'Unknown')}</td><td>${esc(m.sizeBytes||m.size||'Unknown')}</td><td>${esc(m.contextLength||'Unknown')}</td><td>${esc(m.profileId||'None')}</td><td>Not estimated</td><td>${badge('Unverified')}</td><td>${badge(m.state||'registered')}</td></tr>`).join(''):'<tr><td colspan="9">No models registered. Run a scan.</td></tr>'}
function renderOther(){const logs=S.logs||[];const lp=$('.log-console pre');if(lp)lp.textContent=logs.length?logs.map(x=>`[${x.timestamp||x.at||''}] ${(x.level||'info').toUpperCase()} ${x.source||x.category||'system'} ${x.message||''}`).join('\n'):'No backend log evidence recorded.';const ev=$('#evidenceTruth');if(ev)ev.innerHTML=logs.length?logs.slice(0,5).map(x=>`<div class="event-item"><span class="event-icon good">•</span><div><strong>${esc(x.message||'Event')}</strong><p>${esc(x.source||x.category||'system')}</p></div></div>`).join(''):'<div class="empty-state"><p>No backend evidence recorded.</p></div>';const p=$('.profile-grid');if(p)p.innerHTML=S.profiles.length?S.profiles.map(x=>`<div class="content-card profile-card">${badge(x.validationState||'unknown')}<h3>${esc(x.name)}</h3><p>${esc(x.id)}</p></div>`).join(''):'<div class="content-card"><p>No profiles registered.</p></div>';const e=$('.endpoint-grid');if(e)e.innerHTML=`<div class="content-card endpoint-card"><div><h3>Gateway state</h3><p>${esc(S.gateway?.state||'unknown')}</p></div></div><div class="content-card endpoint-card"><div><h3>Capabilities</h3><p>${esc(JSON.stringify(S.capabilities||{}))}</p></div></div>`;const rs=Array.isArray(S.requests)?S.requests:(S.requests?.requests||S.requests?.active||[]);$('#requestTruth').innerHTML=rs.length?rs.map(x=>`<tr><td><code>${esc(x.id||x.requestId||'Unknown')}</code></td><td>${esc(x.route||x.path||'Unknown')}</td><td>${esc(x.state||x.status||'unknown')}</td><td>${x.id||x.requestId?`<button class="text-button danger-text cancelReal" data-id="${esc(x.id||x.requestId)}">Cancel</button>`:''}</td></tr>`).join(''):'<tr><td colspan="4">No requests reported.</td></tr>';$$('.cancelReal').forEach(b=>b.onclick=async()=>{try{await api.cancel(b.dataset.id);await refresh()}catch(e){toast('Cancellation unavailable',err(e),'warning')}});const tel=$('#telemetryTruth');if(tel)tel.innerHTML=`<div class="telemetry-metrics"><div><span>State</span><strong>${esc(S.telemetry?.state||'unavailable')}</strong><small>Backend</small></div><div><span>GPUs</span><strong>${esc((S.telemetry?.local?.gpus||[]).length)}</strong><small>Reported</small></div></div>`}
function renderJobs(){const a=S.jobs.filter(j=>!['completed','failed','cancelled','done'].includes(j.state));$('#jobCount').textContent=a.length;$('#jobList').innerHTML=S.jobs.length?S.jobs.slice(0,20).map(j=>`<div class="job-item"><strong>${esc(j.type||j.id)}</strong><small>${esc(j.phase||j.state||'unknown')}</small><div class="ux-progress"><span style="width:${Math.max(0,Math.min(100,Number(j.progress||0)))}%"></span></div></div>`).join(''):'<div class="empty-state"><p>No backend jobs</p></div>'}
async function waitJob(id){for(let i=0;i<150;i++){const j=await api.job(id);S.jobs=await api.jobs();renderJobs();if(['completed','done'].includes(j.state))return j;if(['failed','cancelled'].includes(j.state))throw new Error(j.error?.message||j.state);await new Promise(r=>setTimeout(r,800))}throw new Error('Job polling timed out')}
async function scan(){try{const j=await api.scan();toast('Model scan accepted',j.id);await waitJob(j.id);await refresh()}catch(e){toast('Model scan failed',err(e),'warning')}}
async function launch(){if(!S.models.length){toast('No models','Run a scan first','warning');return}const modelId=prompt('Model ID to launch',S.models[0].id);if(!modelId)return;try{const p=await api.preflight({modelId});if(!p.launchAllowed){toast('Launch blocked',`Risk ${p.allocation?.risk||'unknown'}`,'warning');return}if(!confirm('Preflight allows launch. Start the real runtime?'))return;const j=await api.launch({modelId});toast('Launch accepted',j.id);await waitJob(j.id);await refresh()}catch(e){toast('Launch failed',err(e),'warning')}}
async function stop(){if(!confirm('Drain requests and stop runtime/workers?'))return;try{const j=await api.stop({force:false});toast('Stop accepted',j.id);await waitJob(j.id);await refresh()}catch(e){toast('Stop failed',err(e),'warning')}}
async function refresh(){const tasks=[api.capabilities(),api.status(),api.machines(),api.models(),api.profiles(),api.jobs(),api.telemetry(),api.logs(),api.requests(),api.gateway()];const keys=['capabilities','status','machines','models','profiles','jobs','telemetry','logs','requests','gateway'];(await Promise.allSettled(tasks)).forEach((r,i)=>{if(r.status==='fulfilled')S[keys[i]]=r.value;else toast(`${keys[i]} unavailable`,err(r.reason),'warning')});renderStatus();renderMachines();renderModels();renderOther();renderJobs();renderWorkspace();renderExtensibility()}
function wire(){nav();$$('.add-machine-trigger,#addMachineBtn,#topologyAddMachine').forEach(b=>b?.addEventListener('click',()=>$('#machineDialog')?.showModal()));$('#scanModelsBtn').onclick=scan;$('#registerModelBtn').onclick=()=>toast('Manual registration unavailable','Use recursive scan; no backend route exists.','warning');$('#stopAllBtn').onclick=stop;$('#unloadModelBtn').onclick=stop;$('#jobsBtn').onclick=()=>$('#jobDrawer').hidden=!$('#jobDrawer').hidden;$('#closeJobsBtn').onclick=()=>$('#jobDrawer').hidden=true;$('#commandPreviewBtn').onclick=()=>toast('Command preview unavailable','No backend contract exists.','warning');$('#inspectProfileBtn').onclick=()=>toast('Profile inspector unavailable','Use the Profiles page.','warning');const q=$('#quickActionGrid');if(q)q.innerHTML='<button class="action-tile" id="scanQuick"><span>⌁</span><strong>Rescan models</strong><small>Backend job</small></button><button class="action-tile add" id="addQuickActionBtn"><span>＋</span><strong>Add action</strong><small>Declarative action</small></button>';$('#scanQuick').onclick=scan;$('#addQuickActionBtn').onclick=()=>$('#actionDialog')?.showModal();$('#machineForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')||'').trim(),address=String(f.get('address')||'').trim();if(!name||!address){toast('Validation failed','Name and address are required','warning');return}const m={id:`machine-${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now().toString().slice(-5)}`,name,addresses:[address],controller:{scheme:'http',port:Number(f.get('controllerPort'))},rpc:{port:Number(f.get('rpcPort')),enabled:true},paths:{runtime:String(f.get('runtimePath')||''),models:String(f.get('modelsPath')||'')},tags:['worker'],enabled:true};try{await api.createMachine(m);e.currentTarget.closest('dialog').close();await refresh()}catch(x){toast('Machine creation failed',err(x),'warning')}});$('#testConnectionBtn').onclick=()=>toast('Save first','Test the saved machine from the Machines page.','neutral')}
neutralize();wire();refresh().catch(e=>toast('Control-plane unavailable',err(e),'warning'));setInterval(()=>refresh().catch(()=>{}),5000);
