const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={onboardingStep:0,launchStep:0,jobs:[],dirty:false,machineStep:0,connectionVerified:false};
function toast(title,msg=''){const e=document.createElement('div');e.className='toast';e.innerHTML=`<strong>${title}</strong><span>${msg}</span>`;$('#toastRegion').append(e);setTimeout(()=>e.remove(),3600)}
function markDirty(v=true){state.dirty=v;const el=$('#saveState');if(!el)return;el.innerHTML=v?'<span class="dirty-dot"></span> Unsaved layout':'<span class="status-dot good"></span> Saved'}
function addJob(title,phases){const job={id:Date.now(),title,phases,index:0,progress:0,state:'running'};state.jobs.unshift(job);renderJobs();$('#jobDrawer').hidden=false;const timer=setInterval(()=>{job.progress+=20;if(job.progress>=100){job.progress=0;job.index++;if(job.index>=job.phases.length){job.state='done';clearInterval(timer);toast(`${title} completed`,'All required evidence checks passed.');setTimeout(()=>{state.jobs=state.jobs.filter(j=>j.id!==job.id);renderJobs()},2200)}}renderJobs()},650)}
function renderJobs(){const list=$('#jobList'),count=$('#jobCount');count.textContent=state.jobs.length;if(!state.jobs.length){list.innerHTML='<div class="empty-state" style="min-height:150px"><p>No active jobs</p></div>';return}list.innerHTML=state.jobs.map(j=>`<div class="job-item"><strong>${j.title}</strong><small>${j.state==='done'?'Completed':j.phases[j.index]}</small><div class="ux-progress"><span style="width:${j.state==='done'?100:j.progress}%"></span></div><div class="job-phase"><span>${j.state==='done'?'Verified':'Running'}</span><span>${j.state==='done'?'100%':Math.min(99,Math.round(((j.index+j.progress/100)/j.phases.length)*100))+'%'}</span></div></div>`).join('')}
$('#jobsBtn')?.addEventListener('click',()=>$('#jobDrawer').hidden=!$('#jobDrawer').hidden);$('#closeJobsBtn')?.addEventListener('click',()=>$('#jobDrawer').hidden=true);

const onboarding=[
 {title:'Choose your starting workspace',body:`<div class="choice-grid"><button type="button" class="choice-card selected"><strong>Operations</strong><small>Runtime, machines, requests and evidence</small></button><button type="button" class="choice-card"><strong>Performance Lab</strong><small>Benchmarks and telemetry first</small></button><button type="button" class="choice-card"><strong>Minimal Monitor</strong><small>Health and alerts only</small></button><button type="button" class="choice-card"><strong>Blank workspace</strong><small>Start with an empty canvas</small></button></div>`},
 {title:'Confirm the host machine',body:`<div class="form-grid two-col"><label>Host name<input value="Host workstation"></label><label>Host address<input value="192.168.1.240"></label><label>Controller port<input value="50053"></label><label>Dashboard port<input value="8088"></label></div><div class="inline-notice" style="margin-top:14px">Services use machine-local paths. Mapped drives are shown only as host conveniences.</div>`},
 {title:'Add your first worker',body:`<div class="choice-grid"><button type="button" class="choice-card selected"><strong>Use detected Worker 01</strong><small>192.168.1.155 · RPC :50052</small></button><button type="button" class="choice-card"><strong>Add another machine</strong><small>Open the full machine wizard after setup</small></button></div>`},
 {title:'Ready to enter the workspace',body:`<div class="validation-list"><div class="validation-row"><span class="status-dot good"></span><strong>Host configuration</strong><small>Valid</small></div><div class="validation-row"><span class="status-dot good"></span><strong>Worker controller</strong><small>Reachable</small></div><div class="validation-row"><span class="status-dot good"></span><strong>Model source</strong><small>Z:\\LLM_Proxy\\Models</small></div><div class="validation-row"><span class="status-dot neutral"></span><strong>Active model</strong><small>Configure later</small></div></div>`}
];
function renderOnboarding(){const s=onboarding[state.onboardingStep];$('#onboardingPanel').innerHTML=`<h3>${s.title}</h3>${s.body}`;$$('.onboarding-steps span').forEach((x,i)=>x.classList.toggle('active',i<=state.onboardingStep));$('#onboardingBack').disabled=state.onboardingStep===0;$('#onboardingNext').textContent=state.onboardingStep===onboarding.length-1?'Enter workspace':'Continue';$$('.choice-card').forEach(c=>c.onclick=()=>{c.parentElement.querySelectorAll('.choice-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')})}
if(!localStorage.getItem('lb-onboarded')){renderOnboarding();setTimeout(()=>$('#onboardingDialog').showModal(),250)}
$('#onboardingNext')?.addEventListener('click',()=>{if(state.onboardingStep<onboarding.length-1){state.onboardingStep++;renderOnboarding()}else{localStorage.setItem('lb-onboarded','1');$('#onboardingDialog').close();toast('Workspace ready','Your initial configuration has been saved.')}});
$('#onboardingBack')?.addEventListener('click',()=>{state.onboardingStep=Math.max(0,state.onboardingStep-1);renderOnboarding()});$('#onboardingSkip')?.addEventListener('click',()=>{localStorage.setItem('lb-onboarded','1');$('#onboardingDialog').close()});

const launchViews=[
 ()=>`<div class="form-grid"><label>Model<select><option>Qwen3.5-27B-Q4_K_M.gguf</option><option>Qwen3.5-9B-Q4_K_M.gguf</option><option>Nemotron-4B-Q8_0.gguf</option></select></label><div class="launch-summary"><div class="summary-card"><span>Architecture</span><strong>Qwen · 27B</strong><small>Q4_K_M · 15.6 GB</small></div><div class="summary-card"><span>Context metadata</span><strong>131K</strong><small>Selected target 64K</small></div></div></div>`,
 ()=>`<div class="choice-grid"><button type="button" class="choice-card selected"><strong>Balanced RPC</strong><small>Host + Worker 01 · 64K · q8_0 KV</small></button><button type="button" class="choice-card"><strong>Host only</strong><small>Lower context · automatic layers</small></button><button type="button" class="choice-card"><strong>Create profile</strong><small>Open profile editor</small></button></div>`,
 ()=>`<div class="validation-list"><div class="validation-row"><span class="status-dot good"></span><strong>GGUF metadata</strong><small>Parsed</small></div><div class="validation-row"><span class="status-dot good"></span><strong>Machine compatibility</strong><small>2 compatible</small></div><div class="validation-row"><span class="status-dot good"></span><strong>Controller and RPC</strong><small>Reachable</small></div><div class="validation-row"><span class="status-dot" style="background:var(--warning)"></span><strong>VRAM headroom</strong><small>1.8 GB · caution</small></div></div><div class="inline-notice" style="margin-top:12px">Advisory estimate only. A 12% safety reserve is applied before launch.</div>`,
 ()=>`<div class="launch-summary"><div class="summary-card"><span>Model</span><strong>Qwen 27B</strong><small>Balanced RPC</small></div><div class="summary-card"><span>Allocation</span><strong>2 machines</strong><small>Host 58% · Worker 31%</small></div><div class="summary-card"><span>Context</span><strong>64K</strong><small>q8_0 KV cache</small></div><div class="summary-card"><span>Gateway</span><strong>:1234 / :11434</strong><small>Health checked after start</small></div></div>`
];
function renderLaunch(){const panel=$('#launchPanel');panel.innerHTML=launchViews[state.launchStep]();$$('#launchSteps span').forEach((x,i)=>{x.classList.toggle('active',i===state.launchStep);x.classList.toggle('done',i<state.launchStep)});$('#launchBack').disabled=state.launchStep===0;$('#launchNext').textContent=state.launchStep===3?'Start model':'Continue';$$('.choice-card',panel).forEach(c=>c.onclick=()=>{c.parentElement.querySelectorAll('.choice-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')})}
$('#launchFlowBtn')?.addEventListener('click',()=>{state.launchStep=0;renderLaunch();$('#launchDialog').showModal()});$('#launchBack')?.addEventListener('click',()=>{state.launchStep=Math.max(0,state.launchStep-1);renderLaunch()});$('#launchNext')?.addEventListener('click',()=>{if(state.launchStep<3){state.launchStep++;renderLaunch()}else{$('#launchDialog').close();addJob('Start Qwen3.5-27B',['Validate configuration','Start worker RPC','Wait for RPC readiness','Start host runtime','Verify API health'])}});
$('#unloadModelBtn')?.addEventListener('click',()=>$('#unloadDialog').showModal());$('#confirmUnloadBtn')?.addEventListener('click',()=>{$('#unloadDialog').close();addJob('Unload active model',['Drain active requests','Stop host runtime','Release worker allocation','Verify memory released'])});
$('#commandPreviewBtn')?.addEventListener('click',()=>toast('Launch command copied','Preview includes resolved profile source and machine allocation.'));$('#inspectProfileBtn')?.addEventListener('click',()=>toast('Profile inspector','Balanced RPC opened in the contextual inspector.'));

$('#customizeBtn')?.addEventListener('click',()=>markDirty(true));$('#doneCustomizeBtn')?.addEventListener('click',()=>{markDirty(false);localStorage.setItem('lb-layout-saved',Date.now())});$('#resetLayoutBtn')?.addEventListener('click',()=>markDirty(true));
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});

document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandPaletteBtn')?.click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();markDirty(false);toast('Workspace saved','Layout and widget settings persisted locally.')}if(e.key==='Escape')$('#jobDrawer').hidden=true});

const originalTest=$('#testConnectionBtn');originalTest?.addEventListener('click',()=>{state.connectionVerified=true;setTimeout(()=>toast('Connection evidence recorded','Controller version, RPC port and paths verified.'),250)});

// Make common prototype actions behave like guided UX rather than dead buttons.
$$('.action-tile').forEach(tile=>{if(!tile.id)tile.addEventListener('click',()=>addJob(tile.querySelector('strong')?.textContent||'Action',['Validate target','Execute action','Verify result']))});
$$('.models-table tbody tr').forEach(row=>row.addEventListener('dblclick',()=>{$('#launchFlowBtn')?.click()}));
