// ============================================
// FORM REGISTRY - Single source of truth for all forms
// ============================================

export const FORM_REGISTRY = {
  // ----- MACHINE FORM -----
  machine: {
    id: 'machine',
    title: 'Add/Edit Machine',
    icon: 'icon-machines',
    layout: 'two-col',
    fields: [
      {
        id: 'name',
        label: 'Machine Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., workstation-01',
        help: 'A friendly name to identify this machine',
      },
      {
        id: 'role',
        label: 'Role',
        type: 'text',
        placeholder: 'host, rpc-worker, custom',
        help: 'Tags to categorize this machine',
      },
      {
        id: 'address',
        label: 'IP Address / Hostname',
        type: 'ip-address',
        required: true,
        placeholder: '192.168.1.100',
        help: 'Network address of the machine',
        validation: {
          pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$|^[a-zA-Z0-9.-]+$',
          message: 'Enter a valid IP address or hostname',
        },
      },
      {
        id: 'controllerPort',
        label: 'Controller Port',
        type: 'port',
        required: true,
        default: 8088,
        min: 1,
        max: 65535,
        help: 'Port for controller communication',
      },
      {
        id: 'rpcPort',
        label: 'RPC Port',
        type: 'port',
        required: true,
        default: 8089,
        min: 1,
        max: 65535,
        help: 'Port for RPC communication',
      },
      {
        id: 'controllerProtocol',
        label: 'Protocol',
        type: 'select',
        options: [
          { value: 'http', label: 'HTTP' },
          { value: 'https', label: 'HTTPS' },
        ],
        default: 'http',
      },
      {
        id: 'runtimePath',
        label: 'Runtime Path',
        type: 'file-picker',
        placeholder: 'Optional: path to llama-server',
        help: 'Full path to the llama-server executable',
        accept: 'application/x-executable, .exe',
        span: 2,
      },
      {
        id: 'modelsPath',
        label: 'Models Path',
        type: 'folder-picker',
        placeholder: 'Optional: path to models directory',
        help: 'Directory containing GGUF model files',
        span: 2,
      },
      {
        id: 'machineActions',
        label: 'Machine Actions',
        type: 'checkbox-group',
        span: 2,
        options: [], // Dynamically populated
      },
      {
        id: 'rpcEnabled',
        label: 'RPC Available',
        type: 'checkbox',
        default: false,
        help: 'Enable RPC on this machine',
      },
      {
        id: 'enabled',
        label: 'Enabled',
        type: 'checkbox',
        default: true,
        help: 'Connect this machine on startup',
      },
    ],
  },

  // ----- PROFILE FORM -----
  profile: {
    id: 'profile',
    title: 'Create/Edit Launch Profile',
    icon: 'icon-profiles',
    layout: 'two-col',
    fields: [
      {
        id: 'name',
        label: 'Profile Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., Default Profile',
      },
      {
        id: 'id',
        label: 'Profile ID',
        type: 'text',
        required: true,
        placeholder: 'e.g., profile-default',
        help: 'Unique identifier (lowercase, hyphens allowed)',
        validation: {
          pattern: '^[a-z0-9][a-z0-9._-]{1,63}$',
          message: 'Use lowercase letters, numbers, dots, hyphens, underscores',
        },
      },
      {
        id: 'contextSize',
        label: 'Context Size',
        type: 'number',
        default: 8192,
        min: 512,
        max: 131072,
        step: 512,
        help: 'Maximum tokens in context window',
      },
      {
        id: 'gpuLayers',
        label: 'GPU Layers',
        type: 'number',
        default: 35,
        min: -1,
        max: 999,
        help: 'Number of layers to offload to GPU (-1 = all)',
      },
      {
        id: 'batchSize',
        label: 'Batch Size',
        type: 'number',
        default: 512,
        min: 1,
        max: 4096,
        help: 'Processing batch size',
      },
      {
        id: 'threads',
        label: 'CPU Threads',
        type: 'number',
        default: 8,
        min: 1,
        max: 128,
        help: 'Number of CPU threads to use',
      },
      {
        id: 'parallel',
        label: 'Parallel Slots',
        type: 'number',
        default: 1,
        min: 1,
        max: 16,
        help: 'Number of parallel request slots',
      },
      {
        id: 'flashAttention',
        label: 'Flash Attention',
        type: 'checkbox',
        default: true,
        help: 'Enable Flash Attention (requires supported build)',
      },
      {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        span: 2,
        rows: 3,
        placeholder: 'Optional description of this profile',
      },
    ],
  },

  // ----- EXTENSION FORM -----
  extension: {
    id: 'extension',
    title: 'Import Extension',
    icon: 'icon-extensions',
    layout: 'full',
    fields: [
      {
        id: 'manifest',
        label: 'JSON Manifest',
        type: 'json-editor',
        required: true,
        span: 2,
        rows: 18,
        placeholder: '{"id":"sample.extension","name":"Sample","version":"1.0.0"}',
        help: 'Paste your declarative extension manifest here. No executable code is allowed.',
      },
    ],
  },

  // ----- ACTION FORM -----
  action: {
    id: 'action',
    title: 'Create/Edit Action',
    icon: 'icon-actions',
    layout: 'two-col',
    fields: [
      {
        id: 'name',
        label: 'Action Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., Scan Models',
      },
      {
        id: 'id',
        label: 'Action ID',
        type: 'text',
        required: true,
        placeholder: 'e.g., scan-models',
        validation: {
          pattern: '^[a-z0-9][a-z0-9._-]{1,63}$',
          message: 'Use lowercase letters, numbers, dots, hyphens, underscores',
        },
      },
      {
        id: 'type',
        label: 'Action Type',
        type: 'select',
        options: [
          { value: 'models-scan', label: 'Model Scan' },
          { value: 'controller-status', label: 'Controller Status' },
          { value: 'rpc-start', label: 'RPC Start' },
          { value: 'rpc-stop', label: 'RPC Stop' },
          { value: 'http-request', label: 'HTTP Request' },
          { value: 'profile-select', label: 'Profile Select' },
        ],
        default: 'models-scan',
      },
      {
        id: 'confirmation',
        label: 'Confirmation',
        type: 'select',
        options: [
          { value: 'dangerous-only', label: 'Dangerous Only' },
          { value: 'always', label: 'Always' },
          { value: 'never', label: 'Never' },
        ],
        default: 'dangerous-only',
      },
      {
        id: 'permissions',
        label: 'Permissions',
        type: 'text',
        span: 2,
        placeholder: 'models.scan, rpc.control',
        help: 'Comma-separated list of permissions',
      },
      {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        span: 2,
        rows: 2,
        placeholder: 'Optional description',
      },
      {
        id: 'config',
        label: 'Config JSON',
        type: 'json-editor',
        span: 2,
        rows: 7,
        default: '{}',
        help: 'Action-specific configuration',
      },
      {
        id: 'enabled',
        label: 'Enabled',
        type: 'checkbox',
        default: true,
      },
    ],
  },

  // ----- ENDPOINT FORM -----
  endpoint: {
    id: 'endpoint',
    title: 'Create/Edit Endpoint',
    icon: 'icon-gateways',
    layout: 'full',
    fields: [
      {
        id: 'name',
        label: 'Endpoint Name',
        type: 'text',
        required: true,
        placeholder: 'e.g., Control Plane API',
      },
      {
        id: 'id',
        label: 'Endpoint ID',
        type: 'text',
        required: true,
        placeholder: 'e.g., endpoint-control-plane',
        validation: {
          pattern: '^[a-z0-9][a-z0-9._-]{1,63}$',
          message: 'Use lowercase letters, numbers, dots, hyphens, underscores',
        },
      },
      {
        id: 'baseUrl',
        label: 'Base URL',
        type: 'url',
        required: true,
        placeholder: 'http://127.0.0.1:8088',
        help: 'Full URL including protocol and port',
      },
      {
        id: 'healthPath',
        label: 'Health Path',
        type: 'text',
        placeholder: '/health',
        help: 'Optional endpoint for health checks',
      },
      {
        id: 'enabled',
        label: 'Enabled',
        type: 'checkbox',
        default: true,
      },
    ],
  },

  // ----- SETTINGS FORM -----
  settings: {
    id: 'settings',
    title: 'Settings',
    icon: 'icon-settings',
    layout: 'grid',
    sections: [
      {
        id: 'paths',
        label: 'Paths',
        fields: [
          {
            id: 'applicationRoot',
            label: 'Application Root',
            type: 'text',
            readonly: true,
            help: 'Running location of the control plane',
          },
          {
            id: 'modelSources',
            label: 'Model Sources',
            type: 'text-list',
            rows: 3,
            placeholder: 'One path per line',
            help: 'Directories containing GGUF files',
          },
          {
            id: 'llamaServerPath',
            label: 'llama-server Executable',
            type: 'file-picker',
            placeholder: 'Optional absolute path',
            accept: 'application/x-executable, .exe',
            help: 'Path to llama-server.exe',
          },
        ],
      },
      {
        id: 'ports',
        label: 'Ports',
        fields: [
          {
            id: 'controllerPort',
            label: 'Worker Controller Port',
            type: 'port',
            default: 8088,
            min: 1,
            max: 65535,
          },
          {
            id: 'rpcPort',
            label: 'RPC Port',
            type: 'port',
            default: 8089,
            min: 1,
            max: 65535,
          },
        ],
      },
      {
        id: 'runtime',
        label: 'Runtime',
        fields: [
          {
            id: 'pollIntervalMs',
            label: 'UI Polling Interval (ms)',
            type: 'number',
            default: 5000,
            min: 1000,
            max: 60000,
            step: 500,
            help: 'How often the UI refreshes data',
          },
          {
            id: 'requestDrainTimeoutSec',
            label: 'Request Drain Timeout (sec)',
            type: 'number',
            default: 30,
            min: 1,
            max: 600,
            help: 'Timeout for draining requests on shutdown',
          },
        ],
      },
      {
        id: 'safety',
        label: 'Safety',
        fields: [
          {
            id: 'blockUnsafeLaunch',
            label: 'Block High-Risk Launches',
            type: 'checkbox',
            default: true,
            help: 'Prevent launches that may exceed VRAM',
          },
        ],
      },
    ],
  },
};